/* Objects literals  
Used to store keyed collections  and complex entities 
property => (key , value) pair
objects are collection of properties. */

let student = {
    name:"Hassan",
    age: 23,
    marks: 80

};
console.log(student.marks);

// Thread / Twitter Post
/* Creating an object literal for the
 properties of thread / twitter post includes 
 -> username
 -> content
 -> likes
 -> reports
 -> tags */

 const post = {
    username : "@muhammadhassan",
    content : "Developer Road-Map",
    likes : 200,
    reports : 5,
    tags : ["@apnacollege", "@developerroadmap"]

 };

 /* Get values 
   1: (object name.property)  we use object name a dot and property
   2:(object name["property"]) in this we use object name and then square brackets and inside
   square brackets properties are written in side double quotes
   
   */

 console.log(post.username); //method 1 
 console.log(post.tags[0]);  // method 1 
 console.log(post["content"]); //method 2

/* Add , Update and delete Values */

student.name = "Zaynab"; // updated name
console.log(`Updated student name : ${student.name}`);

student.age = 17;
console.log(`Updated student age : ${student.age}.`);

console.log(`Updated Student object :`, student);

delete student.marks; // it will delete that specific property.

console.log(`After deleting marks property :`, student);

// Nested and Array of Objects


const classInfo = 

 [
    {
      name : "ali" ,
      grade : "A+",
      city : "Lahore"  
    },

    {
      name : "umer",    
      grade : "B+", 
      city : "Karachi"  
    },

    {
      name : "umair",     
      grade : "A", 
      city : "Islamabad" 
    }
  
];
console.log(classInfo[1].name ,"   ",classInfo[2].grade,"  ",classInfo[0].city);
console.log(classInfo[0]);
classInfo[0].grade = "C+";
console.log("After updating the grades of first object :",classInfo[0]) 

/*Math Objest  
  1 - Math.abs(x) it will return the value in absolute form (convert negative number into positive ) 
   2 - Math.pow(x,y) it is use to calculate the power of a number.
   3 - Math.floor(x) to round of nearest smallest integer value.
   4 - Math.ceil(x)  to round of nearest largest  integer value.
   5 - Math.random(x) it gives random value between 0 to 1 and 1 is exclusive.
*/
console.log("Absolute value of -4 is :",Math,abs(-4)); // output : 4
console.log("6 ^ 5 is: ",Math.pow(6,5));// output : 7776
console.log("Nearest  or smallest value of 7.2 is : ",Math.floor(7.2)); // Output : 7 
console.log("Nearest  or largest value of 7.2 is : ",Math.ceil(7.2)); // Output : 8
console.log("Random numbers between 0 to 1 are : ",Math.random()); // output : 0.37202420219989973


// Random Integers from 1 to 10
// Step 1 get a random number.
let random = Math.random();
// Step 2 multiply that random number you generated by the number you want to get random number from 1 to n.
random = random * 10;
// Step 3 use floor method to gte the decmal number into whole number.
random  = Math.floor(random);
//Step 4 to get the exact number you entered add 1 in last.
random = random+1;

